# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'managed': True, 'verbose_name': 'Search', 'verbose_name_plural': 'Searchs'},
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'managed': True, 'verbose_name': 'SearchResult', 'verbose_name_plural': 'SearchResults'},
        ),
        migrations.AlterModelTable(
            name='search',
            table='connector_search',
        ),
        migrations.AlterModelTable(
            name='searchresult',
            table='connector_searchresult',
        ),
    ]
