# Generated by Django 2.0.5 on 2018-05-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180515_0653'),
        ('connector', '0019_auto_20180516_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskqueues', to='app.LinkedInUser'),
        ),
    ]
