# Generated by Django 2.0.5 on 2018-05-16 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0020_taskqueue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
