# Generated by Django 2.0.5 on 2018-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_freebotip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
    ]
